SELECT SUM(COST) FROM PETRESCUE;
SELECT SUM(COST) AS SUM_OF_COST FROM PETRESCUE;
SELECT MAX(QUANTITY) FROM PETRESCUE;
SELECT AVG(COST) FROM PETRESCUE;
SELECT AVG(COST/QUANTITY) FROM PETRESCUE WHERE ANIMAL = "dog";
SELECT ANIMAL, ROUND(COST) FROM PETRESCUE;
SELECT LENGTH(ANIMAL) FROM PETRESCUE;
SELECT DISTINCT (UCASE(ANIMAL)) FROM PETRESCUE; 
SELECT * FROM PETRESCUE WHERE ANIMAL = 'cat';
SELECT DAY(RESCUEDATE) FROM PETRESCUE WHERE ANIMAL = 'cat';
SELECT COUNT(*) AS cantidad_rescates
FROM PETRESCUE
WHERE MONTH(RESCUEDATE) = '05';
SELECT COUNT(*) AS cantidad_rescates
FROM PETRESCUE
WHERE DAY(RESCUEDATE) = '14';
SELECT DATE_ADD(RESCUEDATE, INTERVAL 3 DAY) FROM PETRESCUE;
SELECT DATEDIFF(CURRENT_TIMESTAMP, RESCUEDATE) FROM PETRESCUE;